export const data = [
  {
    name: "Jan",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Feb",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Mar",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Apr",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "May",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Jun",
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Jul",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Aug",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Sept",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Oct",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Nov",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Dec",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Snow",
    avatar: "./img/image-intro-desktop.jpg",
    email: "ebuka@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Felix",
    avatar: "./img/image-intro-desktop.jpg",
    email: "felix@gmail.com",
    status: "active",
    transaction: "$140.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Apple Ipod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$250.00",
  },
  {
    id: 3,
    name: "Dell Latitude",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$600.00",
  },
  {
    id: 4,
    name: "Iphone X",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$1000.00",
  },
  {
    id: 5,
    name: "Iphone 7",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$900.00",
  },
  {
    id: 6,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpod",
    image: "./img/image-intro-desktop.jpg",
    stock: "123",
    status: "active",
    price: "$140.00",
  },
];

export const productData = [
  {
    name: "Jan",
    sales: 4000,
  },
  {
    name: "Feb",
    sales: 3000,
  },
  {
    name: "Mar",
    sales: 5000,
  },
  {
    name: "Apr",
    sales: 2000,
  },
  {
    name: "May",
    sales: 8000,
  },
  {
    name: "June",
    sales: 7000,
  },
  {
    name: "July",
    sales: 9000,
  },
  {
    name: "August",
    sales: 10000,
  },
]